INSERT INTO song (id, artist, name) VALUES (nextval('song_id_seq'), 'Imagine Dragons', 'Radioactive');
INSERT INTO song (id, artist, name) VALUES (nextval('song_id_seq'), 'Rihanna', 'Diamonds');
INSERT INTO song (id, artist, name) VALUES (nextval('song_id_seq'), 'Justin Bieber', 'Ghost');
INSERT INTO song (id, artist, name) VALUES (nextval('song_id_seq'), 'Billie Eilish', 'Ocean Eyes');
INSERT INTO song (id, artist, name) VALUES (nextval('song_id_seq'), 'Coldplay', 'Yellow');
INSERT INTO song (id, artist, name) VALUES (nextval('song_id_seq'), 'Adele', 'Someone Like You');
INSERT INTO song (id, artist, name) VALUES (nextval('song_id_seq'), 'Drake', 'Hotline Bling');
INSERT INTO song (id, artist, name) VALUES (nextval('song_id_seq'), 'Bruno Mars', 'Grenade');
INSERT INTO song (id, artist, name) VALUES (nextval('song_id_seq'), 'Taylor Swift', 'Blank Space');
INSERT INTO song (id, artist, name) VALUES (nextval('song_id_seq'), 'Maroon 5', 'Sugar');
INSERT INTO song (id, artist, name) VALUES (nextval('song_id_seq'), 'Camila Cabello', 'Never Be the Same');
INSERT INTO song (id, artist, name) VALUES (nextval('song_id_seq'), 'Shawn Mendes', 'There’s Nothing Holdin’ Me Back');
INSERT INTO song (id, artist, name) VALUES (nextval('song_id_seq'), 'Post Malone', 'Wow.');
INSERT INTO song (id, artist, name) VALUES (nextval('song_id_seq'), 'Selena Gomez', 'Lose You to Love Me');
INSERT INTO song (id, artist, name) VALUES (nextval('song_id_seq'), 'Halsey', 'Without Me');
INSERT INTO song (id, artist, name) VALUES (nextval('song_id_seq'), 'Sia', 'Cheap Thrills');
INSERT INTO song (id, artist, name) VALUES (nextval('song_id_seq'), 'OneRepublic', 'Counting Stars');
INSERT INTO song (id, artist, name) VALUES (nextval('song_id_seq'), 'Khalid', 'Talk');
INSERT INTO song (id, artist, name) VALUES (nextval('song_id_seq'), 'Miley Cyrus', 'Flowers');
INSERT INTO song (id, artist, name) VALUES (nextval('song_id_seq'), 'Zayn', 'Pillowtalk');
INSERT INTO song (id, artist, name) VALUES (nextval('song_id_seq'), 'Sam Smith', 'Stay With Me');
INSERT INTO song (id, artist, name) VALUES (nextval('song_id_seq'), 'Nicki Minaj', 'Super Bass');
INSERT INTO song (id, artist, name) VALUES (nextval('song_id_seq'), 'Doja Cat', 'Say So');
INSERT INTO song (id, artist, name) VALUES (nextval('song_id_seq'), 'Olivia Rodrigo', 'Good 4 U');
INSERT INTO song (id, artist, name) VALUES (nextval('song_id_seq'), 'Harry Styles', 'As It Was');
INSERT INTO song (id, artist, name) VALUES (nextval('song_id_seq'), 'Charlie Puth', 'Attention');
INSERT INTO song (id, artist, name) VALUES (nextval('song_id_seq'), 'Jason Derulo', 'Savage Love');